type User {
    _id: ID!
    firstName: String!
    lastName: String!
    fullName: String!
    email: String!
    active: Boolean!
}

input CreateUserInput {
    firstName: String!
    lastName: String!
    email: String
    active: Boolean!
}

input UpdateUserInput {
    firstName: String
    lastName: String
    email: String
    active: Boolean
}

type Query {
    users: [User!]!
    user(id: ID!): User!
}

type Mutation {
    createUser(data: CreateUserInput!): User!
    updateUser(id: ID!, data: UpdateUserInput!): User!
    deleteUser(id: ID!): Boolean
}